version: "3.8"

services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: civic-educator-ai
    ports:
      - "8000:8000"
    volumes:
      - ./knowledge_base:/app/knowledge_base
      - ./data:/app/data
      - ./hf-cache:/root/.cache/huggingface
      - ./wheels:/wheels  # Mount pre-downloaded wheels into container
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HF_HOME=/root/.cache/huggingface
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
